name: setup
description: A new Flutter project.

publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

environment:
  sdk: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - images/pii.jpg


  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source
      fonts:
        - asset: fonts/SourceSans3-Regular.ttf
